# Generated by Django 5.2.1 on 2026-05-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='application',
            name='activities',
        ),
        migrations.AddField(
            model_name='application',
            name='activities',
            field=models.ManyToManyField(blank=True, help_text='Select extracurricular activities.', to='backend.activity'),
        ),
    ]
